/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class GetPid */

#ifndef _Included_GetPid
#define _Included_GetPid
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     GetPid
 * Method:    getPid
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_GetPid_getPid
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
